<link rel="stylesheet" href="<?php echo $this->getSkinUrl('pagsegurodireto/css/styles.css') ?>" type="text/css" />
<p><?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?></p>
<?php if ($_specificInfo = $this->getSpecificInformation()): ?>
    <table class="form-list" cellspacing="0">
        <tbody>
            <?php foreach ($_specificInfo as $_label => $_value): 
                if($_label == 'Mensagem') {
                } else {?>
                <tr>
                    <td class="value"><?php echo nl2br(implode($this->getValueAsArray($_value, false), "\n")) ?></td>
                </tr>
            <?php } endforeach; ?>
        </tbody>
    </table>
<?php endif;

echo $this->getChildHtml();